### ISSUE TITLE
Request to Add Icon: IconBrandGoogle to Package

### ISSUE THREAD

**Issue by k-ardliyan** [irsyadadl/paranoid#1]
Halo bang @irsyadadl 👋,

Saya ingin meminta penambahan ikon **IconBrandGoogle** ke dalam _package_. Ikon ini merupakan pilihan yang populer dan pasti berguna untuk pengguna lainnya. Terima kasih telah mempertimbangkan permintaan ini.

Salam,
@k-ardliyan

**Comment by irsyadadl** [comment]
Already in: [Check here](https://paranoid.irsyad.co/?search=google)
