### ISSUE TITLE
Support for React 19

### ISSUE THREAD

**Issue by dongnguyenvn** [irsyadadl/paranoid#3]
I have encountered an issue where the current version of paranoid does not support React 19. This is impacting our ability to upgrade and leverage the new features and improvements in React 19.

**Comment by irsyadadl** [comment]
Yep. Still working on it.

**Comment by irsyadadl** [comment]
@dongnguyenvn can you check this [repo](https://github.com/irsyadadl/next-15-paranoid). It's paranoid using react 19.

You have to make sure you using the latest version, and also, watch you `tsconfig.json` to always `"skipLibCheck": true,`.
